"""
backup_bot.py — Push bot source code to the private solBotCode repo
====================================================================

Daily-ish snapshot of the bot's CODE (not state) to a private GitHub
repo so a hardware failure doesn't lose the strategy work. Mirrors a
curated set of files into ~/Desktop/solBotCode/ then commits + pushes.

NEVER backed up:
  • .env (private key)
  • thebigshortbus-*.json (Google service account)
  • sol_*.json (state — regenerates on its own)
  • _*.json (research scratch — gigabytes of throwaway data)
  • bot_output.log / bot.log / dashboard.log
  • __pycache__/

Run modes:
    python backup_bot.py            # one-shot: copy + commit + push
    python backup_bot.py --dry-run  # show what would be copied/committed
    python backup_bot.py --no-push  # commit locally but skip git push

Wired into degen_bot.py to auto-run once every 24 hours when the bot
is alive. Also safe to run manually any time you want a forced backup.
"""

import os
import sys
import shutil
import subprocess
import json
from datetime import datetime
from pathlib import Path

# ────────────────────────────────────────────────────────────────────────────
# What gets backed up. Each entry maps a SOURCE path (relative to the bot
# project root or absolute) to a DESTINATION path inside the backup repo.
# Files that don't exist locally are silently skipped — making the file
# list aspirational rather than fragile.
# ────────────────────────────────────────────────────────────────────────────

BOT_ROOT = Path(__file__).parent.resolve()
BACKUP_ROOT = (BOT_ROOT.parent / "solBotCode").resolve()
SCHEDULED_TASKS_DIR = Path.home() / ".claude" / "scheduled-tasks"

# Code files (the actual bot)
CODE_FILES = [
    "degen_bot.py",
    "dashboard.py",
    "sheets_sync.py",
    "build_static_dashboard.py",
    "publish_dashboard.py",
    "backup_bot.py",
]

# Prompt files (agent definitions — these are AS critical as the code)
PROMPT_FILES = [
    "scheduled-task-prompt.md",
    "research-brain-prompt.md",
    "maintenance-agent-prompt.md",
    "efficiency-lab-prompt.md",  # renamed from memory-keeper-prompt.md (May 2026)
    "memory-keeper-prompt.md",   # legacy — kept in backup until next 30-day archival cycle
]

# Project docs
DOC_FILES = [
    "CLAUDE.md",
    "RECOVERY.md",
    "README.md",
    "requirements.txt",
]

# Brain memory — these were updated by the Claude brain routine (deleted
# 2026-05-17). sol_brain_directives.json removed from the list since the
# routine that wrote it is gone. sol_survival_history.json + sol_pinned_wallets.json
# are still written by the bot itself, worth keeping in the backup set.
# Missing files are silently skipped by the copy logic.
BRAIN_MEMORY_FILES = [
    "sol_survival_history.json",
    "sol_pinned_wallets.json",
]


def env_example_template() -> str:
    """Generate a sanitized .env.example so a fresh-clone setup knows
    which env vars to fill in. Reads keys from the real .env (without
    values) — never the values themselves."""
    real_env = BOT_ROOT / ".env"
    if not real_env.exists():
        return ""
    lines = ["# .env.example — fill in the real values, then rename to .env",
             "# Generated by backup_bot.py — values are NEVER copied.",
             ""]
    for line in real_env.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key = line.split("=", 1)[0].strip()
            lines.append(f"{key}=")
    return "\n".join(lines) + "\n"


def backup_gitignore() -> str:
    """The .gitignore for the BACKUP repo — different from the public one.
    Allows everything we explicitly copy in; denies anything we don't."""
    return """# Backup repo .gitignore — keeps secrets out even if a future
# backup_bot.py change accidentally tries to copy them.

# Hard deny secrets and state
.env
.env.local
*.pem
*.key
*-credentials.json
thebigshortbus*.json

# Hard deny operational state files (these regenerate)
sol_heartbeat.json
sol_positions.json
sol_budget_state.json
sol_trade_log.json
sol_events.json
sol_wallet_scan.json
sol_strategy_stats.json
sol_brain_status.json
sol_research_status.json
sol_research_findings.json
sol_research_history.json
sol_maintenance_status.json
sol_maintenance_log.json
sol_memory_keeper_status.json
sol_memory_keeper_log.json
sol_survival_report.json
sol_target_wallets.json
sol_holder_snapshots.json
sol_deposits.json
sol_todo_list.json
sol_brain_split_evaluation.json
sol_wiring_check_report.json

# Research scratch
_*.json
_*.pkl
_*.py

# Build artifacts and noise
__pycache__/
*.pyc
*.log
bot_output.log
dashboard.log
node_modules/
cloudflared.exe
docs/data/

# Scratch directories
backups/
"""


# ────────────────────────────────────────────────────────────────────────────
# Copy logic — purely additive. Never deletes from the backup repo.
# A removed source file leaves its old backup intact (good — accidental
# deletion in the live tree shouldn't propagate to backup).
# ────────────────────────────────────────────────────────────────────────────


def copy_file_if_present(src: Path, dst: Path, dry_run: bool = False) -> bool:
    if not src.exists() or not src.is_file():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dry_run:
        # Compare sizes so dry-run shows what would change
        if dst.exists() and dst.stat().st_size == src.stat().st_size:
            return False  # likely unchanged
        return True
    shutil.copy2(src, dst)
    return True


def copy_all(dry_run: bool = False) -> dict:
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)
    counts = {"copied": 0, "skipped_missing": 0, "scheduled_tasks": 0}

    # 1. Code + prompts + docs + brain memory
    for filename in CODE_FILES + PROMPT_FILES + DOC_FILES + BRAIN_MEMORY_FILES:
        src = BOT_ROOT / filename
        dst = BACKUP_ROOT / filename
        if copy_file_if_present(src, dst, dry_run):
            counts["copied"] += 1
        elif not src.exists():
            counts["skipped_missing"] += 1

    # 2. Scheduled-task SKILL.md files (live in ~/.claude/, separate location)
    if SCHEDULED_TASKS_DIR.exists():
        for task_dir in SCHEDULED_TASKS_DIR.iterdir():
            skill = task_dir / "SKILL.md"
            if skill.exists():
                dst = BACKUP_ROOT / ".claude" / "scheduled-tasks" / task_dir.name / "SKILL.md"
                if copy_file_if_present(skill, dst, dry_run):
                    counts["scheduled_tasks"] += 1

    # 3. .env.example (synthesized — never has real values)
    env_template = env_example_template()
    if env_template:
        env_dst = BACKUP_ROOT / ".env.example"
        if dry_run:
            counts["copied"] += 1 if not env_dst.exists() or env_dst.read_text(encoding="utf-8") != env_template else 0
        else:
            env_dst.write_text(env_template, encoding="utf-8")
            counts["copied"] += 1

    # 4. Backup .gitignore (always overwrite — it's our safety net)
    if not dry_run:
        (BACKUP_ROOT / ".gitignore").write_text(backup_gitignore(), encoding="utf-8")

    return counts


# ────────────────────────────────────────────────────────────────────────────
# Git operations — only inside BACKUP_ROOT. Never touches the bot's repo.
# ────────────────────────────────────────────────────────────────────────────


_CREATE_NO_WINDOW = 0x08000000 if sys.platform == "win32" else 0


def _git(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd, cwd=BACKUP_ROOT, check=check,
        capture_output=True, text=True,
        creationflags=_CREATE_NO_WINDOW,
    )


def commit_and_push(dry_run: bool = False, no_push: bool = False) -> tuple[bool, str]:
    """Returns (success, message)."""
    # Stage everything in the backup repo (the .gitignore protects us from
    # accidentally including secrets that we never copied in).
    _git(["git", "add", "-A"], check=False)

    diff = _git(["git", "diff", "--cached", "--name-only"], check=False)
    changed_files = diff.stdout.strip().splitlines()
    if not changed_files:
        return True, "no changes — backup already up to date"

    msg = f"backup {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    if dry_run:
        return True, f"dry-run: would commit {len(changed_files)} file(s): {', '.join(changed_files[:6])}{'…' if len(changed_files) > 6 else ''}"

    commit = _git(["git", "commit", "-m", msg], check=False)
    if commit.returncode != 0:
        return False, f"commit failed: {commit.stderr.strip()}"

    if no_push:
        return True, f"committed locally ({len(changed_files)} files), --no-push"

    push = _git(["git", "push", "origin", "HEAD"], check=False)
    if push.returncode != 0:
        return False, f"committed but push failed: {push.stderr.strip()}"

    return True, f"backed up {len(changed_files)} file(s) → solBotCode"


# ────────────────────────────────────────────────────────────────────────────


def write_log_entry(success: bool, message: str, counts: dict):
    """Append to sol_backup_log.json so the dashboard / operator can see
    when the last successful backup ran."""
    log_file = BOT_ROOT / "sol_backup_log.json"
    try:
        entries = json.loads(log_file.read_text(encoding="utf-8")) if log_file.exists() else []
    except Exception:
        entries = []
    entries.append({
        "ts": datetime.now().strftime("%Y-%m-%d %H:%M:%S EDT"),
        "ok": success,
        "message": message,
        "counts": counts,
    })
    # Keep last 100 entries to bound size
    entries = entries[-100:]
    log_file.write_text(json.dumps(entries, indent=2), encoding="utf-8")


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    no_push = "--no-push" in args

    if not BACKUP_ROOT.exists():
        print(f"ERROR: backup repo not cloned at {BACKUP_ROOT}")
        print(f"Run first: cd {BACKUP_ROOT.parent} && git clone https://github.com/JPMendenhall/solBotCode.git")
        sys.exit(1)

    print(f"[backup] source: {BOT_ROOT}")
    print(f"[backup] target: {BACKUP_ROOT}")
    print(f"[backup] mode:   {'dry-run' if dry_run else ('no-push' if no_push else 'commit+push')}")

    counts = copy_all(dry_run=dry_run)
    print(f"[backup] copied: {counts['copied']} files (+ {counts['scheduled_tasks']} scheduled-task SKILL.md)")
    if counts["skipped_missing"]:
        print(f"[backup] skipped (not present locally): {counts['skipped_missing']}")

    success, message = commit_and_push(dry_run=dry_run, no_push=no_push)
    print(f"[backup] {message}")

    if not dry_run:
        write_log_entry(success, message, counts)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
